# ====== ACCELERATION ======
ACCELERATE_MAX_X = 1500  # mm/s2, M201 X
ACCELERATE_MAX_Y = 1500  # mm/s2, M201 Y
ACCELERATE_MAX_Z = 200  # mm/s2, M201 Z
ACCELERATE_MAX_E = 10000  # mm/s2, M201 E
ACCELERATE_PRINT = 1500.00  # mm/s2, M204 S
ACCELERATE_RETRACT = 1000.00  # mm/s2, M204 R
ACCELERATE_TRAVEL = 2000.00  # mm/s2, M204 T
MIN_SEGMENT_TIME = 20000  # µs, M205 B

# ====== STEPS PER MM ======
STEPS_PER_MM_X = 160.00  # steps, M92 X
STEPS_PER_MM_Y = 160.00  # steps, M92 Y
STEPS_PER_MM_Z = 800.00  # steps, M92 Z
STEPS_PER_MM_E = 821.00  # steps, M92 E

# ====== SPEED ======
SPEED_MAX_X = 250.00  # mm/s, M203 X
SPEED_MAX_Y = 250.00  # mm/s, M203 Y
SPEED_MAX_Z = 50.00  # mm/s, M203 Z
SPEED_MAX_E = 25.00  # mm/s, M203 E

# ====== JERKS ======
JERK_MAX_X = 10.00  # M205 X
JERK_MAX_Y = 10.00  # M205 Y
JERK_MAX_Z = 0.50  # M205 Z
JERK_MAX_E = 10.00  # M205 E

# ====== STEPPERS ======
STEPPER_INVERT_X = No  
STEPPER_INVERT_Y = Yes  
STEPPER_INVERT_Z1 = Yes  
STEPPER_INVERT_Z2_TO_Z1 = No  # invert Z2 with respect to Z1
STEPPER_INVERT_E = Yes  

# ====== HOME OFFSET ======
HOME_OFFSET_X = 0.00  # mm, M206 X
HOME_OFFSET_Y = 0.00  # mm, M206 Y
HOME_OFFSET_Z = 0.00  # mm, M206 Z

# ====== FILAMENT RUNOUT SENSOR ======
FILAMENTSENSOR_ENABLED = Yes  # M412 S
FILAMENTSENSOR_DISTANCE = 300.00  # M412 D

# ====== BED LEVELING ======
BEDLEVEL_FADE_HEIGHT = 3.00  # mm
BEDLEVEL_BLTOUCH_ENABLED = Yes  
BEDLEVEL_BLTOUCH_INVERT = No  
BEDLEVEL_BLTOUCH_OFFSET_X = 8.40  # mm, M851 X
BEDLEVEL_BLTOUCH_OFFSET_Y = 32.40  # mm, M851 Y
BEDLEVEL_BLTOUCH_OFFSET_Z = -0.842  # mm, M851 Z
BEDLEVEL_POINTS_X = 4  
BEDLEVEL_POINTS_Y = 4  
BEDLEVEL_Z_VALUES = -0.073, -0.031, 0.056, -0.024, 0.000, 0.000, -0.125, -0.101, -0.025, -0.055, 0.000, 0.000, -0.119, -0.145, -0.053, -0.070, 0.000, 0.000, -0.099, -0.132, -0.067, -0.027, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000  # mm

# ====== ENDSTOPS ======
ENDSTOP_INVERT_X = Yes  
ENDSTOP_INVERT_Y = Yes  
ENDSTOP_INVERT_Z1 = Yes  
ENDSTOP_INVERT_Z2 = Yes  
ENDSTOP_ADJUST_Z2 = 0.000  # mm

# ====== TEMPERATURE ======
PREHEAT_HOTEND_1 = 40  # °C, hotend temperature
PREHEAT_BED_1 = 80  # °C, bed temperature
PREHEAT_FAN_1 = 0  # fan speed
PREHEAT_HOTEND_2 = 235  # °C, hotend temperature
PREHEAT_BED_2 = 110  # °C, bed temperature
PREHEAT_FAN_2 = 0  # fan speed
PID_HOTEND_P = 9.91000  
PID_HOTEND_I = 0.08800  
PID_HOTEND_D = 281.18753  
PID_BED_P = 60.35000  
PID_BED_I = 1.52800  
PID_BED_D = 1589.12500  
THERMISTOR_TYPE_HOTEND = 0  # 0 - Epcos 100k (1), 1 - ATC 104GT/104NT 100k (5), 2 - Hisens 3950 100k (13), 3 - Formbot b3950 100k (61), 4 - Dyze D500 4.7M (66), 5 - Pt1000 4.7kΩ pullup (1047)
THERMISTOR_TYPE_BED = 0  # 0 - Epcos 100k (1), 1 - ATC 104GT/104NT 100k (5), 2 - Hisens 3950 100k (13), 3 - Formbot b3950 100k (61), 4 - Dyze D500 4.7M (66), 5 - Pt1000 4.7kΩ pullup (1047)

# ====== LCD ======
LCD_BRIGHTNESS = 19  # 0-19
LCD_TOUCH_X = -16642  # do not change!
LCD_TOUCH_Y = 11484  # do not change!
LCD_TOUCH_OFFSET_X = 504  # do not change!
LCD_TOUCH_OFFSET_Y = -24  # do not change!
LCD_LANGUAGE = 1  # 0 - English, 1 - Русский

# ====== PSU ======
PSU_ENABLED = No  

# ====== FW RETRACT ======
FWRETRACT_LENGTH = 2.00  # mm, M207 S - G10 Retract length
FWRETRACT_SPEED = 20.00  # mm/s, M207 F - G10 Retract feedrate
FWRETRACT_Z_HOP = 0.50  # mm, M207 Z - G10 Retract hop size
FWRETRACT_RECOVER_LENGTH = 0.00  # mm, M208 S - G11 Recover extra length
FWRETRACT_RECOVER_SPEED = 20.00  # mm/s, M208 F - G11 Recover feedrate
FWRETRACT_SWP_LENGTH = 13.00  # mm, M207 W - G10 Swap Retract length
FWRETRACT_RECOVER_SWP_LENGTH = 0.00  # mm, G11 Swap Recover length
FWRETRACT_RECOVER_SWP_SPEED = 20.00  # mm/s, G11 Swap Recover feedrate

# ====== LINEAR ADVANCE ======
LA_KFACTOR = 0.0000  # Linear Advance K-factor, M900 K

# ====== PARKING / FILAMENT CHANGE ======
PARK_POINT_X = 330.0  # mm, X coordinate for parking (pause or filament change)
PARK_POINT_Y = 290.0  # mm, Y coordinate for parking (pause or filament change)
PARK_POINT_Z = 10.0  # mm, Z lift for parking (pause or filament change)
PARK_MOVE_SPEED = 100.0  # mm/s, move to parking feedrate
PARK_RETR_SPEED = 30.0  # mm/s, feedrate of retract before parking
PARK_RETR_LENGTH = 3.0  # mm, length of retract before parking
PARK_HEATER_TIMEOUT = 45  # s, timeout for disable hotend heater
UNLOAD_SPEED = 10.0  # mm/s, feedrate of unload filament in filament change
UNLOAD_LENGTH = 100.0  # mm, length of unload filament in filament change
SLOW_LOAD_SPEED = 6.0  # mm/s, feedrate of slow load filament in filament change
SLOW_LOAD_LENGTH = 0.0  # mm, length of slow load filament in filament change
FAST_LOAD_SPEED = 6.0  # mm/s, feedrate of fast load filament in filament change
FAST_LOAD_LENGTH = 0.0  # mm, length of fast load filament in filament change
